### PR TITLE
Added cross-fetch polyfill

### PR DESCRIPTION
**Pull request by rschwabco**

### CODE REVIEW

**Comment by theluk** [comment]
Can we merge it any time soon?

**Comment by egoist** [comment]
I think this will break Cloudflare Worker usage https://github.com/lquixada/cross-fetch/issues/69

**Comment by rschwabco** [comment]
@egoist I'm afraid we might have to live with that for the time being. 

@theluk - I'm still testing this to ensure there are no backward-compatability issues.

**Comment by junhyeokkwak** [comment]
Seems like this issue was resolved at `0.0.10` but was then reintroduced in`0.0.11`

**Pull request merged**
